# -*- coding: utf-8 -*-

from odoo import models, fields, api, _
from odoo.exceptions import UserError, ValidationError

class SaleOrder(models.Model):
    _inherit = 'sale.order'
    
    sale_user_group_id = fields.Many2one(
        'sale.user.group',
        string='Sales Person Group',
    )
    
    @api.multi
    @api.onchange('partner_id')
    def onchange_partner_id(self):
        print 'cussssssssssssssssssssss',self.partner_id
        print 'ccccccccccccccccccccccccccccccccccc',self.partner_id.sale_user_group_id
        self.sale_user_group_id = self.partner_id.sale_user_group_id.id
        res = super(SaleOrder, self).onchange_partner_id()
        return res
        
        
    @api.multi
    def _prepare_invoice(self):
        print 'innnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn'
        print 'invoicennnnnnnnnnnnnnnnnnnnnnnnnnnnn',self.sale_user_group_id
        result = super(SaleOrder, self)._prepare_invoice()
        sale_user_group_id = self.sale_user_group_id.id
        result.update({'sale_user_group_id':sale_user_group_id})
        return result

class SaleAdvancePaymentInv(models.TransientModel):
    _inherit = "sale.advance.payment.inv"
    
    @api.multi
    def _create_invoice(self, order, so_line, amount):
        res = super(SaleAdvancePaymentInv, self)._create_invoice(order, so_line, amount)
        sale_user_group_id = self.sale_user_group_id
        res.update({'sale_user_group_id':sale_user_group_id})
        return res

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
